# Generated by Django 5.1.1 on 2024-11-14 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transacoes', '0003_alter_transacao_options_remove_categoria_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='classificacao',
        ),
        migrations.AddField(
            model_name='transacao',
            name='classificacao',
            field=models.CharField(blank=True, choices=[('VA', 'Variável'), ('FX', 'Fixa')], max_length=2, null=True, verbose_name='Classificação'),
        ),
    ]
