# Generated by Django 5.1.1 on 2025-03-21 01:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome do Banco')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='bancos/logos/', verbose_name='Logo do Banco')),
                ('status', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
        ),
        migrations.CreateModel(
            name='ContaBancaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cartao_credito', models.BooleanField(default=False)),
                ('descricao', models.CharField(max_length=50)),
                ('conta', models.CharField(max_length=20)),
                ('agencia', models.CharField(max_length=20, verbose_name='Agência')),
                ('saldo_inicial', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.BooleanField(default=True, verbose_name='Ativo')),
                ('banco', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bancos.banco')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricoSaldo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('movimento', models.DecimalField(decimal_places=2, max_digits=10)),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='bancos.contabancaria')),
            ],
        ),
    ]
