# Generated by Django 5.1.1 on 2025-02-21 01:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bancos', '0001_initial'),
        ('financeiro', '0002_rename_cadastro_historicalmovimentacao_pessoa_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contabancaria',
            old_name='nome',
            new_name='descricao',
        ),
        migrations.RemoveField(
            model_name='contabancaria',
            name='saldo_atual',
        ),
        migrations.RemoveField(
            model_name='historicosaldo',
            name='valor_anterior',
        ),
        migrations.RemoveField(
            model_name='historicosaldo',
            name='valor_atual',
        ),
        migrations.AddField(
            model_name='historicosaldo',
            name='movimentacao',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='historico_saldo', to='financeiro.movimentacao'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='historicosaldo',
            name='conta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='bancos.contabancaria'),
        ),
    ]
