# Generated by Django 5.1.1 on 2024-10-18 01:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bancos', '0001_initial'),
        ('clientes', '0001_initial'),
        ('operacoes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movimentacoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(blank=True, max_length=200, null=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('data', models.DateField()),
                ('situacao', models.CharField(choices=[('PG', 'Pago'), ('AP', 'A pagar')], default='AP', max_length=2)),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bancos.contabancaria')),
                ('tipo_pagamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagamentos', to='operacoes.tipopagamento')),
            ],
            options={
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='Entrada',
            fields=[
                ('movimentacoes_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='movimentacoes.movimentacoes')),
                ('cliente', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='clientes.cliente')),
                ('tipo_receita', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='receitas', to='operacoes.tiporeceita')),
            ],
            bases=('movimentacoes.movimentacoes',),
        ),
        migrations.CreateModel(
            name='Saida',
            fields=[
                ('movimentacoes_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='movimentacoes.movimentacoes')),
                ('tipo_despesa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='despesas', to='operacoes.tipodespesa')),
            ],
            bases=('movimentacoes.movimentacoes',),
        ),
    ]
