# Generated by Django 5.1.1 on 2024-10-01 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimentacoes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='banco',
            name='saldo_atual',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
    ]
