# Generated by Django 5.1.1 on 2024-10-01 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimentacoes', '0002_banco_saldo_atual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banco',
            name='saldo_atual',
            field=models.DecimalField(auto_created=True, blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
    ]
