# Generated by Django 5.1.1 on 2024-10-04 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimentacoes', '0003_alter_banco_saldo_atual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banco',
            name='status',
            field=models.CharField(choices=[('AT', 'Ativo'), ('IN', 'Inativo')], default='AT', max_length=10),
        ),
        migrations.AlterField(
            model_name='entrada',
            name='situacao',
            field=models.CharField(choices=[('PG', 'Pago'), ('AP', 'A pagar')], max_length=2),
        ),
        migrations.AlterField(
            model_name='saida',
            name='situacao',
            field=models.CharField(choices=[('PG', 'Pago'), ('AP', 'A pagar')], max_length=2),
        ),
        migrations.AlterField(
            model_name='tipo',
            name='status',
            field=models.CharField(choices=[('AT', 'Ativo'), ('IN', 'Inativo')], default='AT', max_length=10),
        ),
    ]
