# Generated by Django 5.1.1 on 2024-10-08 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimentacoes', '0004_alter_banco_status_alter_entrada_situacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrada',
            name='situacao',
            field=models.CharField(choices=[('PG', 'Pago'), ('AP', 'A pagar')], default='AP', max_length=2),
        ),
    ]
