# Generated by Django 5.1.1 on 2024-10-08 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimentacoes', '0005_alter_entrada_situacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saida',
            name='situacao',
            field=models.CharField(choices=[('PG', 'Pago'), ('AP', 'A pagar')], default='AP', max_length=2),
        ),
    ]
