# Generated by Django 5.1.1 on 2024-10-09 00:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bancos', '0001_initial'),
        ('movimentacoes', '0006_alter_saida_situacao'),
        ('operacoes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saida',
            name='banco',
        ),
        migrations.RemoveField(
            model_name='entrada',
            name='banco',
        ),
        migrations.AlterField(
            model_name='saida',
            name='tipo_despesa',
            field=models.ForeignKey(limit_choices_to={'tipo': 'despesa'}, on_delete=django.db.models.deletion.PROTECT, related_name='despesas_saida', to='operacoes.tipo'),
        ),
        migrations.AlterField(
            model_name='saida',
            name='tipo_pagamento',
            field=models.ForeignKey(limit_choices_to={'tipo': 'pagamento'}, on_delete=django.db.models.deletion.PROTECT, related_name='saidas', to='operacoes.tipo'),
        ),
        migrations.AlterField(
            model_name='entrada',
            name='tipo_entrada',
            field=models.ForeignKey(limit_choices_to={'tipo': 'entrada'}, on_delete=django.db.models.deletion.PROTECT, related_name='entradas', to='operacoes.tipo'),
        ),
        migrations.AlterField(
            model_name='entrada',
            name='tipo_pagamento',
            field=models.ForeignKey(limit_choices_to={'tipo': 'pagamento'}, on_delete=django.db.models.deletion.PROTECT, related_name='pagamentos', to='operacoes.tipo'),
        ),
        migrations.AlterModelOptions(
            name='entrada',
            options={'ordering': ['-data']},
        ),
        migrations.AlterModelOptions(
            name='saida',
            options={'ordering': ['-data']},
        ),
        migrations.AddField(
            model_name='entrada',
            name='conta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='bancos.contabancaria'),
        ),
        migrations.AddField(
            model_name='saida',
            name='conta',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, to='bancos.contabancaria'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Banco',
        ),
        migrations.DeleteModel(
            name='Tipo',
        ),
    ]
