# Generated by Django 5.1.1 on 2024-10-09 00:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bancos', '0001_initial'),
        ('movimentacoes', '0007_remove_saida_banco_remove_entrada_banco_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saida',
            name='conta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='bancos.contabancaria'),
        ),
    ]
