# Generated by Django 5.1.1 on 2024-10-09 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movimentacoes', '0008_alter_saida_conta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entrada',
            name='tipo_entrada',
        ),
    ]
