# Generated by Django 5.1.1 on 2024-10-09 01:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimentacoes', '0009_remove_entrada_tipo_entrada'),
        ('operacoes', '0002_tipodespesa_tipopagamento_tiporeceita'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrada',
            name='tipo_receita',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receitas', to='operacoes.tiporeceita'),
        ),
        migrations.AlterField(
            model_name='entrada',
            name='tipo_pagamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagamentos', to='operacoes.tipopagamento'),
        ),
        migrations.AlterField(
            model_name='saida',
            name='tipo_despesa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='despesas_saida', to='operacoes.tipodespesa'),
        ),
        migrations.AlterField(
            model_name='saida',
            name='tipo_pagamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='saidas', to='operacoes.tipopagamento'),
        ),
    ]
