# Generated by Django 5.1.1 on 2024-10-09 02:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bancos', '0001_initial'),
        ('clientes', '0005_alter_cliente_cnpj_cpf'),
        ('movimentacoes', '0012_alter_entrada_tipo_receita'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrada',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clientes.cliente'),
        ),
        migrations.AlterField(
            model_name='entrada',
            name='conta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bancos.contabancaria'),
        ),
    ]
