# Generated by Django 5.1.1 on 2024-10-11 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimentacoes', '0013_alter_entrada_cliente_alter_entrada_conta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrada',
            name='data',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='saida',
            name='data',
            field=models.DateField(),
        ),
    ]
