# Generated by Django 5.1.1 on 2025-03-28 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_customuser_first_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='email',
        ),
    ]
