# Generated by Django 5.1.1 on 2025-04-01 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_customuser_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='email',
        ),
    ]
