# Generated by Django 5.1.1 on 2025-03-21 01:27

import django.db.models.deletion
import django.utils.timezone
import simple_history.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bancos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CondicaoPagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
                ('numero_parcelas', models.PositiveIntegerField(default=1)),
                ('juros', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='FormaRecebimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='HistoricoTransacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_movimentacao', models.DateField(auto_now=True)),
                ('tipo_movimentacao', models.CharField(choices=[('RE', 'Receita'), ('DE', 'Despesa')], max_length=2)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('saldo_anterior', models.DecimalField(decimal_places=2, max_digits=10)),
                ('saldo_posterior', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Movimentacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_movimentacao', models.CharField(choices=[('RE', 'Receita'), ('DE', 'Despesa')], max_length=2)),
                ('descricao', models.CharField(max_length=255)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_movimentacao', models.DateField(default=django.utils.timezone.now)),
                ('data_vencimento', models.DateField()),
            ],
            options={
                'verbose_name': 'Movimentação',
                'verbose_name_plural': 'Movimentações',
            },
        ),
        migrations.CreateModel(
            name='Parcela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(verbose_name='Número da Parcela')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pago', models.BooleanField(default=False, verbose_name='Pago')),
                ('data_vencimento', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='PermissaoFinanceira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pode_criar_movimentacao', models.BooleanField(default=False)),
                ('pode_editar_movimentacao', models.BooleanField(default=False)),
                ('pode_excluir_movimentacao', models.BooleanField(default=False)),
                ('pode_ver_todas_movimentacoes', models.BooleanField(default=False)),
                ('pode_gerenciar_cartoes', models.BooleanField(default=False)),
                ('pode_gerenciar_usuarios', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='CartaoCredito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('dia_corte', models.PositiveIntegerField(help_text='Dia do mês em que fecha a fatura')),
                ('dia_vencimento', models.PositiveIntegerField(help_text='Dia do mês para pagamento da fatura')),
                ('limite', models.DecimalField(decimal_places=2, max_digits=10)),
                ('limite_disponivel', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ativo', models.BooleanField(default=True)),
                ('banco', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bancos.contabancaria')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalMovimentacao',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('tipo_movimentacao', models.CharField(choices=[('RE', 'Receita'), ('DE', 'Despesa')], max_length=2)),
                ('descricao', models.CharField(max_length=255)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_movimentacao', models.DateField(default=django.utils.timezone.now)),
                ('data_vencimento', models.DateField()),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('cartao_credito', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='financeiro.cartaocredito')),
            ],
            options={
                'verbose_name': 'historical Movimentação',
                'verbose_name_plural': 'historical Movimentações',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
