# Generated by Django 5.1.1 on 2025-01-15 02:10

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bancos', '0003_alter_banco_status_alter_contabancaria_agencia_and_more'),
        ('cadastro', '0010_alter_cadastro_nome_fantasia'),
        ('operacoes', '0002_alter_centrodecusto_responsavel'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormaRecebimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Movimentacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_movimentacao', models.DateField(default=django.utils.timezone.now, verbose_name='Data Movimentação')),
                ('descricao', models.CharField(max_length=50)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('parcelado', models.BooleanField(default=False, verbose_name='Parcelado')),
                ('data_vencimento', models.DateField()),
                ('cadastro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastro.cadastro', verbose_name='Cliente/Fornecedor')),
                ('centro_de_custo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='operacoes.centrodecusto', verbose_name='Centro de Custo')),
                ('conta_bancaria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bancos.contabancaria', verbose_name='Conta Bancária')),
                ('forma_recebimento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='financeiro.formarecebimento')),
                ('natureza_financeira', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='operacoes.naturezafinanceira', verbose_name='Natureza Financeira')),
            ],
        ),
        migrations.CreateModel(
            name='Parcela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(verbose_name='Número de Parcelas')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_vencimento', models.DateField()),
                ('movimentacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcelas', to='financeiro.movimentacao')),
            ],
        ),
        migrations.CreateModel(
            name='RateioCentroDeCusto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_rateio', models.CharField(choices=[('VA', 'Valor'), ('PO', 'Porcentagem')], default='VA', max_length=2, verbose_name='Tipo de Rateio')),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor do Rateio')),
                ('percentual', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Percentual de Rateio')),
                ('centro_de_custo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='operacoes.centrodecusto', verbose_name='Centro de Custo')),
                ('movimentacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rateios', to='financeiro.movimentacao')),
            ],
        ),
    ]
