# Generated by Django 5.1.1 on 2025-02-19 01:50

import django.db.models.deletion
import django.utils.timezone
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bancos', '0001_initial'),
        ('cadastro', '0001_initial'),
        ('operacoes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CondicaoPagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
                ('numero_parcelas', models.PositiveIntegerField(default=1)),
                ('juros', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='FormaRecebimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalMovimentacao',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('tipo_movimentacao', models.CharField(choices=[('RE', 'Receita'), ('DE', 'Despesa')], max_length=2)),
                ('data_movimentacao', models.DateField(default=django.utils.timezone.now)),
                ('descricao', models.CharField(max_length=255)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_vencimento', models.DateField()),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('cadastro', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='cadastro.pessoa')),
                ('centro_de_custo', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='operacoes.centrodecusto')),
                ('condicao_pagamento', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='financeiro.condicaopagamento')),
                ('conta_bancaria', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='bancos.contabancaria')),
                ('forma_recebimento', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='financeiro.formarecebimento')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('natureza_financeira', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='operacoes.naturezafinanceira')),
            ],
            options={
                'verbose_name': 'historical Movimentação',
                'verbose_name_plural': 'historical Movimentações',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Movimentacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_movimentacao', models.CharField(choices=[('RE', 'Receita'), ('DE', 'Despesa')], max_length=2)),
                ('data_movimentacao', models.DateField(default=django.utils.timezone.now)),
                ('descricao', models.CharField(max_length=255)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_vencimento', models.DateField()),
                ('cadastro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastro.pessoa')),
                ('centro_de_custo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='operacoes.centrodecusto')),
                ('condicao_pagamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='financeiro.condicaopagamento')),
                ('conta_bancaria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bancos.contabancaria')),
                ('forma_recebimento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='financeiro.formarecebimento')),
                ('natureza_financeira', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='operacoes.naturezafinanceira')),
            ],
            options={
                'verbose_name': 'Movimentação',
                'verbose_name_plural': 'Movimentações',
            },
        ),
        migrations.CreateModel(
            name='HistoricoTransacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_movimentacao', models.DateField(auto_now=True)),
                ('tipo_movimentacao', models.CharField(choices=[('RE', 'Receita'), ('DE', 'Despesa')], max_length=2)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('saldo_anterior', models.DecimalField(decimal_places=2, max_digits=10)),
                ('saldo_posterior', models.DecimalField(decimal_places=2, max_digits=10)),
                ('conta_bancaria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bancos.contabancaria')),
                ('transacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_transacao', to='financeiro.movimentacao')),
            ],
        ),
        migrations.CreateModel(
            name='Parcela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(verbose_name='Número da Parcela')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pago', models.BooleanField(default=False, verbose_name='Pago')),
                ('data_vencimento', models.DateField()),
                ('movimentacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcelas', to='financeiro.movimentacao')),
            ],
        ),
        migrations.CreateModel(
            name='RateioCentroDeCusto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_rateio', models.CharField(choices=[('VA', 'Valor'), ('PO', 'Porcentagem')], default='VA', max_length=2, verbose_name='Tipo de Rateio')),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('percentual', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('centro_de_custo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='operacoes.centrodecusto', verbose_name='Centro de Custo')),
                ('movimentacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rateios', to='financeiro.movimentacao')),
            ],
        ),
    ]
