# Generated by Django 5.1.1 on 2025-01-24 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimentacao',
            name='total_parcelas',
            field=models.PositiveIntegerField(blank=True, help_text='Informe o número total de parcelas se a movimentação for parcelada.', null=True, verbose_name='Total de Parcelas'),
        ),
        migrations.AlterUniqueTogether(
            name='parcela',
            unique_together={('movimentacao', 'numero')},
        ),
    ]
