# Generated by Django 5.1.1 on 2025-03-21 01:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bancos', '0002_initial'),
        ('cadastro', '0001_initial'),
        ('financeiro', '0001_initial'),
        ('operacoes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmovimentacao',
            name='centro_de_custo',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='operacoes.centrodecusto'),
        ),
        migrations.AddField(
            model_name='historicalmovimentacao',
            name='condicao_pagamento',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='financeiro.condicaopagamento'),
        ),
        migrations.AddField(
            model_name='historicalmovimentacao',
            name='conta_bancaria',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='bancos.contabancaria'),
        ),
        migrations.AddField(
            model_name='historicalmovimentacao',
            name='forma_recebimento',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='financeiro.formarecebimento'),
        ),
        migrations.AddField(
            model_name='historicalmovimentacao',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalmovimentacao',
            name='natureza_financeira',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='operacoes.naturezafinanceira'),
        ),
        migrations.AddField(
            model_name='historicalmovimentacao',
            name='pessoa',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='cadastro.pessoa'),
        ),
        migrations.AddField(
            model_name='historicalmovimentacao',
            name='usuario',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicotransacao',
            name='conta_bancaria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bancos.contabancaria'),
        ),
        migrations.AddField(
            model_name='movimentacao',
            name='cartao_credito',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='financeiro.cartaocredito'),
        ),
        migrations.AddField(
            model_name='movimentacao',
            name='centro_de_custo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='operacoes.centrodecusto'),
        ),
        migrations.AddField(
            model_name='movimentacao',
            name='condicao_pagamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='financeiro.condicaopagamento'),
        ),
        migrations.AddField(
            model_name='movimentacao',
            name='conta_bancaria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bancos.contabancaria'),
        ),
        migrations.AddField(
            model_name='movimentacao',
            name='forma_recebimento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='financeiro.formarecebimento'),
        ),
        migrations.AddField(
            model_name='movimentacao',
            name='natureza_financeira',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='operacoes.naturezafinanceira'),
        ),
        migrations.AddField(
            model_name='movimentacao',
            name='pessoa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastro.pessoa'),
        ),
        migrations.AddField(
            model_name='movimentacao',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicotransacao',
            name='transacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_transacao', to='financeiro.movimentacao'),
        ),
        migrations.AddField(
            model_name='parcela',
            name='movimentacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcelas', to='financeiro.movimentacao'),
        ),
        migrations.AddField(
            model_name='permissaofinanceira',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
