# Generated by Django 5.1.1 on 2024-12-11 01:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='centrodecusto',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='centrodecusto',
            name='pai',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_centros', to='financeiro.centrodecusto'),
        ),
        migrations.AddField(
            model_name='naturezafinanceira',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='naturezafinanceira',
            name='pai',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_naturezas', to='financeiro.naturezafinanceira'),
        ),
        migrations.AlterField(
            model_name='naturezafinanceira',
            name='sinal',
            field=models.CharField(choices=[('DE', 'Débito'), ('CR', 'Crédito'), ('TR', 'Transitório')], max_length=2),
        ),
    ]
