# Generated by Django 5.1.1 on 2024-12-12 01:09

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bancos', '0003_alter_banco_status_alter_contabancaria_agencia_and_more'),
        ('cadastro', '0007_alter_cadastro_cnpj_cpf'),
        ('financeiro', '0002_centrodecusto_descricao_centrodecusto_pai_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperacaoFinanceira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True)),
                ('descricao', models.CharField(blank=True, max_length=200, null=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('data_vencimento', models.DateField(default=django.utils.timezone.now)),
                ('pago', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('centro_de_custo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operacao_centro', to='financeiro.centrodecusto')),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bancos.contabancaria')),
                ('natureza_financeira', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operacao_natureza', to='financeiro.naturezafinanceira')),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operacao_pessoa', to='cadastro.cadastro')),
            ],
            options={
                'ordering': ['-data_vencimento'],
            },
        ),
    ]
