# Generated by Django 5.1.1 on 2025-01-28 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0002_movimentacao_total_parcelas_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movimentacao',
            options={'verbose_name': 'Movimentação', 'verbose_name_plural': 'Movimentações'},
        ),
        migrations.AddField(
            model_name='movimentacao',
            name='pago',
            field=models.BooleanField(default=False, verbose_name='Pago'),
        ),
        migrations.AddField(
            model_name='parcela',
            name='pago',
            field=models.BooleanField(default=False, verbose_name='Pago'),
        ),
    ]
