# Generated by Django 5.1.1 on 2025-01-30 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0003_alter_movimentacao_options_movimentacao_pago_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movimentacao',
            options={},
        ),
        migrations.AddField(
            model_name='movimentacao',
            name='tipo_movimentacao',
            field=models.CharField(blank=True, choices=[('RE', 'Receita'), ('PA', 'Pagar')], max_length=2, null=True, verbose_name='Tipo de Movimentação'),
        ),
        migrations.AlterField(
            model_name='formarecebimento',
            name='nome',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='movimentacao',
            name='descricao',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='parcela',
            name='numero',
            field=models.PositiveIntegerField(verbose_name='Número da Parcela'),
        ),
        migrations.AlterField(
            model_name='rateiocentrodecusto',
            name='percentual',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='rateiocentrodecusto',
            name='valor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
