# Generated by Django 5.1.1 on 2025-01-30 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0004_alter_movimentacao_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimentacao',
            name='tipo_movimentacao',
            field=models.CharField(choices=[('RE', 'Receita'), ('PA', 'Pagar')], max_length=2, verbose_name='Tipo de Movimentação'),
        ),
    ]
