# Generated by Django 5.1.1 on 2025-01-30 01:01

import django.db.models.deletion
import django.utils.timezone
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bancos', '0004_historicosaldo'),
        ('cadastro', '0010_alter_cadastro_nome_fantasia'),
        ('financeiro', '0005_alter_movimentacao_tipo_movimentacao'),
        ('operacoes', '0002_alter_centrodecusto_responsavel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movimentacao',
            options={'verbose_name': 'Movimentação', 'verbose_name_plural': 'Movimentações'},
        ),
        migrations.AlterField(
            model_name='movimentacao',
            name='tipo_movimentacao',
            field=models.CharField(choices=[('RE', 'Receita'), ('DE', 'Despesa')], max_length=2, verbose_name='Tipo de Movimentação'),
        ),
        migrations.CreateModel(
            name='HistoricalMovimentacao',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('tipo_movimentacao', models.CharField(choices=[('RE', 'Receita'), ('DE', 'Despesa')], max_length=2, verbose_name='Tipo de Movimentação')),
                ('data_movimentacao', models.DateField(default=django.utils.timezone.now, verbose_name='Data Movimentação')),
                ('descricao', models.CharField(max_length=255)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('parcelado', models.BooleanField(default=False, verbose_name='Parcelado')),
                ('total_parcelas', models.PositiveIntegerField(blank=True, help_text='Informe o número total de parcelas se a movimentação for parcelada.', null=True, verbose_name='Total de Parcelas')),
                ('data_vencimento', models.DateField()),
                ('pago', models.BooleanField(default=False, verbose_name='Pago')),
                ('history_change_reason', models.TextField(null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('cadastro', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='cadastro.cadastro', verbose_name='Cliente/Fornecedor')),
                ('centro_de_custo', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='operacoes.centrodecusto', verbose_name='Centro de Custo')),
                ('conta_bancaria', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='bancos.contabancaria', verbose_name='Conta Bancária')),
                ('forma_recebimento', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='financeiro.formarecebimento')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('natureza_financeira', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='operacoes.naturezafinanceira', verbose_name='Natureza Financeira')),
            ],
            options={
                'verbose_name': 'historical Movimentação',
                'verbose_name_plural': 'historical Movimentações',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
