# Generated by Django 5.1.1 on 2025-02-05 01:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bancos', '0004_historicosaldo'),
        ('financeiro', '0006_alter_movimentacao_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoTransacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_movimentacao', models.DateField(auto_now=True)),
                ('tipo_movimentacao', models.CharField(choices=[('RE', 'Receita'), ('DE', 'Despesa')], max_length=2)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('saldo_anterior', models.DecimalField(decimal_places=2, max_digits=10)),
                ('saldo_posterior', models.DecimalField(decimal_places=2, max_digits=10)),
                ('conta_bancaria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bancos.contabancaria')),
                ('transacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_transacao', to='financeiro.movimentacao')),
            ],
        ),
    ]
