# Generated by Django 5.1.1 on 2025-02-08 02:16

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bancos', '0004_historicosaldo'),
        ('cadastro', '0010_alter_cadastro_nome_fantasia'),
        ('financeiro', '0007_historicotransacao'),
        ('operacoes', '0002_alter_centrodecusto_responsavel'),
    ]

    operations = [
        migrations.CreateModel(
            name='CondicaoPagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
                ('numero_parcelas', models.PositiveIntegerField(default=1)),
                ('juros', models.FloatField(default=0)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='parcela',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='historicalmovimentacao',
            name='pago',
        ),
        migrations.RemoveField(
            model_name='historicalmovimentacao',
            name='parcelado',
        ),
        migrations.RemoveField(
            model_name='historicalmovimentacao',
            name='total_parcelas',
        ),
        migrations.RemoveField(
            model_name='movimentacao',
            name='pago',
        ),
        migrations.RemoveField(
            model_name='movimentacao',
            name='parcelado',
        ),
        migrations.RemoveField(
            model_name='movimentacao',
            name='total_parcelas',
        ),
        migrations.AlterField(
            model_name='historicalmovimentacao',
            name='cadastro',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='cadastro.cadastro'),
        ),
        migrations.AlterField(
            model_name='historicalmovimentacao',
            name='centro_de_custo',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='operacoes.centrodecusto'),
        ),
        migrations.AlterField(
            model_name='historicalmovimentacao',
            name='conta_bancaria',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='bancos.contabancaria'),
        ),
        migrations.AlterField(
            model_name='historicalmovimentacao',
            name='data_movimentacao',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='historicalmovimentacao',
            name='history_change_reason',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicalmovimentacao',
            name='natureza_financeira',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='operacoes.naturezafinanceira'),
        ),
        migrations.AlterField(
            model_name='historicalmovimentacao',
            name='tipo_movimentacao',
            field=models.CharField(choices=[('RE', 'Receita'), ('DE', 'Despesa')], max_length=2),
        ),
        migrations.AlterField(
            model_name='movimentacao',
            name='cadastro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastro.cadastro'),
        ),
        migrations.AlterField(
            model_name='movimentacao',
            name='centro_de_custo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='operacoes.centrodecusto'),
        ),
        migrations.AlterField(
            model_name='movimentacao',
            name='conta_bancaria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bancos.contabancaria'),
        ),
        migrations.AlterField(
            model_name='movimentacao',
            name='data_movimentacao',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='movimentacao',
            name='natureza_financeira',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='operacoes.naturezafinanceira'),
        ),
        migrations.AlterField(
            model_name='movimentacao',
            name='tipo_movimentacao',
            field=models.CharField(choices=[('RE', 'Receita'), ('DE', 'Despesa')], max_length=2),
        ),
        migrations.AddField(
            model_name='historicalmovimentacao',
            name='condicao_pagamento',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='financeiro.condicaopagamento'),
        ),
        migrations.AddField(
            model_name='movimentacao',
            name='condicao_pagamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='financeiro.condicaopagamento'),
        ),
    ]
