# Generated by Django 5.1.1 on 2025-02-08 02:16

import django.db.models.deletion
from django.db import migrations, models



class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0008_condicaopagamento_alter_parcela_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimentacao',
            name='condicao_pagamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='financeiro.condicaopagamento'),
        ),
    ]
