# Generated by Django 5.1.1 on 2025-02-08 02:24

from django.db import migrations, models

def criar_condicao_pagamento_padrao(apps, schema_editor):
    CondicaoPagamento = apps.get_model("financeiro", "CondicaoPagamento")  # Obtém o modelo correto
    if not CondicaoPagamento.objects.filter(nome="À Vista Sem Juros").exists():
        CondicaoPagamento.objects.create(nome="À Vista Sem Juros", numero_parcelas=1, juros=0)


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0009_alter_movimentacao_condicao_pagamento'),
    ]

    operations = [
        migrations.RunPython(criar_condicao_pagamento_padrao),
        migrations.AddField(
            model_name='condicaopagamento',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
    ]
