# Generated by Django 5.1.1 on 2024-11-28 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atributo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('CL', 'Cliente'), ('FO', 'Fornecedor'), ('CO', 'Colaborador')], max_length=2, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cadastro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('nome_fantasia', models.CharField(max_length=80)),
                ('cnpj_cpf', models.CharField(max_length=18, unique=True)),
                ('endereco', models.CharField(max_length=100)),
                ('cep', models.CharField(max_length=9)),
                ('municipio', models.CharField(max_length=50)),
                ('estado', models.CharField(max_length=2)),
                ('atributos', models.ManyToManyField(related_name='cadastros', to='cadastro.atributo')),
            ],
        ),
    ]
