# Generated by Django 5.1.1 on 2025-03-21 01:27

import cadastro.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atributo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('CL', 'Cliente'), ('FO', 'Fornecedor'), ('CO', 'Colaborador')], max_length=2, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tipo_pessoa', models.CharField(choices=[('PF', 'Pessoa Física'), ('PJ', 'Pessoa Jurídica'), ('ET', 'Estrangeiro')], max_length=2)),
                ('nome', models.CharField(max_length=200)),
                ('nome_fantasia', models.CharField(blank=True, max_length=80, null=True, verbose_name='Nome Fantasia')),
                ('cnpj_cpf', models.CharField(blank=True, max_length=18, null=True, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(max_length=11)),
                ('atributos', models.ManyToManyField(related_name='pessoas', to='cadastro.atributo')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cep', models.CharField(max_length=9, validators=[cadastro.models.valida_cep])),
                ('logradouro', models.CharField(max_length=100)),
                ('numero', models.CharField(max_length=10)),
                ('complemento', models.CharField(blank=True, max_length=40, null=True)),
                ('referencia', models.CharField(blank=True, max_length=100, null=True)),
                ('bairro', models.CharField(max_length=50)),
                ('municipio', models.CharField(max_length=50)),
                ('estado', models.CharField(max_length=2)),
                ('pais', models.CharField(max_length=20)),
                ('principal', models.BooleanField(default=True)),
                ('pessoa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enderecos', to='cadastro.pessoa')),
            ],
        ),
    ]
