# Generated by Django 5.1.1 on 2025-03-25 01:25

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pessoa',
            name='atributos',
        ),
        migrations.DeleteModel(
            name='Atributo',
        ),
        migrations.AddField(
            model_name='pessoa',
            name='atributos',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('CL', 'Cliente'), ('FO', 'Fornecedor'), ('CO', 'Colaborador')], max_length=2), blank=True, default=list, size=None),
        ),
    ]
