# Generated by Django 5.1.1 on 2024-11-28 00:30

from django.db import migrations

def criar_atributos(apps, schema_editor):
    Atributo = apps.get_model('cadastro', 'Atributo')
    Atributos = [
        ('CL', 'Cliente'),
        ('FO', 'Fornecedor'),
        ('CO', 'Colaborador'),
    ]

    for tipo, nome in Atributos:
        Atributo.objects.get_or_create(tipo=tipo)

class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(criar_atributos),
    ]
