# Generated by Django 5.1.1 on 2025-02-20 00:05

from ..models import Atributos
from django.db import migrations, models

def create_atributos(apps, schema_editor):
    Atributo = apps.get_model("cadastro", "Atributo")

    for atributo in Atributos:
        Atributo.objects.get_or_create(tipo=atributo.value)


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='atributos',
            field=models.ManyToManyField(related_name='pessoas', to='cadastro.atributo'),
        ),

        migrations.RunPython(create_atributos)
    ]
