# Generated by Django 5.1.1 on 2024-11-28 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0002_auto_20241127_2130'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadastro',
            name='tipo_pessoa',
            field=models.CharField(choices=[('PF', 'Pessoa Física'), ('PJ', 'Pessoa Jurídica')], default='PF', max_length=2),
        ),
    ]
