# Generated by Django 5.1.1 on 2025-02-21 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0002_alter_pessoa_atributos'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='endereco',
            name='unique_principal_endereco_per_pessoa',
        ),
        migrations.RemoveField(
            model_name='endereco',
            name='tipo',
        ),
        migrations.AddField(
            model_name='endereco',
            name='principal',
            field=models.BooleanField(default=True),
        ),
    ]
