# Generated by Django 5.1.1 on 2025-03-26 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0002_remove_pessoa_atributos_delete_atributo_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='endereco',
            constraint=models.UniqueConstraint(condition=models.Q(('principal', True)), fields=('pessoa',), name='unique_principal_endereco'),
        ),
    ]
