# Generated by Django 5.1.1 on 2025-02-21 02:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0003_remove_endereco_unique_principal_endereco_per_pessoa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endereco',
            name='pessoa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enderecos', to='cadastro.pessoa'),
        ),
    ]
