# Generated by Django 5.1.1 on 2024-11-28 01:38

import cadastro.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0003_cadastro_tipo_pessoa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cep', models.CharField(max_length=9)),
                ('logradouro', models.CharField(max_length=100)),
                ('numero', models.CharField(max_length=10)),
                ('complemento', models.CharField(blank=True, max_length=40, null=True)),
                ('referencia', models.CharField(blank=True, max_length=100, null=True)),
                ('bairro', models.CharField(max_length=50)),
                ('municipio', models.CharField(max_length=50)),
                ('estado', models.CharField(max_length=2)),
                ('pais', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='cadastro',
            name='cep',
        ),
        migrations.RemoveField(
            model_name='cadastro',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='cadastro',
            name='municipio',
        ),
        migrations.AddField(
            model_name='cadastro',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cadastro',
            name='email',
            field=models.EmailField(default=django.utils.timezone.now, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cadastro',
            name='telefone',
            field=models.CharField(default=django.utils.timezone.now, max_length=11),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cadastro',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='cnpj_cpf',
            field=models.CharField(max_length=18, unique=True, validators=[cadastro.models.validar_cpf_cnpj]),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='tipo_pessoa',
            field=models.CharField(choices=[('PF', 'Pessoa Física'), ('PJ', 'Pessoa Jurídica'), ('ET', 'Estrangeiro')], default='PF', max_length=2),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='endereco',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cadastro.endereco'),
        ),
    ]
