# Generated by Django 5.1.1 on 2024-12-10 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0004_endereco_remove_cadastro_cep_remove_cadastro_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastro',
            name='tipo_pessoa',
            field=models.CharField(choices=[('PF', 'Pessoa Física'), ('PJ', 'Pessoa Jurídica'), ('ET', 'Estrangeiro')], max_length=2),
        ),
    ]
