# Generated by Django 5.1.1 on 2024-12-10 00:30

import cadastro.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0005_alter_cadastro_tipo_pessoa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastro',
            name='cnpj_cpf',
            field=models.CharField(blank=True, max_length=18, unique=True, validators=[cadastro.models.validar_cpf_cnpj]),
        ),
    ]
