# Generated by Django 5.1.1 on 2024-12-10 00:31

import cadastro.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0006_alter_cadastro_cnpj_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastro',
            name='cnpj_cpf',
            field=models.CharField(blank=True, max_length=18, null=True, unique=True, validators=[cadastro.models.validar_cpf_cnpj]),
        ),
    ]
