# Generated by Django 5.1.1 on 2025-01-11 03:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0007_alter_cadastro_cnpj_cpf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cadastro',
            name='endereco',
        ),
        migrations.AddField(
            model_name='endereco',
            name='cadastro',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enderecos', to='cadastro.cadastro'),
        ),
        migrations.AddField(
            model_name='endereco',
            name='tipo',
            field=models.CharField(choices=[('PR', 'Principal'), ('SE', 'Secundário')], default='PR', max_length=2),
        ),
        migrations.AddConstraint(
            model_name='endereco',
            constraint=models.UniqueConstraint(condition=models.Q(('tipo', 'PR')), fields=('cadastro', 'tipo'), name='unique_principal_endereco_per_cadastro'),
        ),
    ]
