# Generated by Django 5.1.1 on 2025-01-14 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0008_remove_cadastro_endereco_endereco_cadastro_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastro',
            name='nome_fantasia',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
