# Generated by Django 5.1.1 on 2025-01-15 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0009_alter_cadastro_nome_fantasia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastro',
            name='nome_fantasia',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Nome Fantasia'),
        ),
    ]
