# Generated by Django 5.1.1 on 2025-03-21 01:27

import django.db.models.deletion
import mptt.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastro', '0001_initial'),
        ('financeiro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CentroDeCusto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('titulo', models.CharField(max_length=50)),
                ('status', models.BooleanField(default=True)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subcentros', to='operacoes.centrodecusto')),
                ('responsavel', models.ForeignKey(blank=True, limit_choices_to={'atributos__tipo': 'CO'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='centros_responsaveis', to='cadastro.pessoa')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NaturezaFinanceira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('titulo', models.CharField(max_length=50)),
                ('tipo', models.CharField(choices=[('ST', 'Sintética'), ('AN', 'Analítica')], max_length=2)),
                ('sinal', models.CharField(choices=[('CR', 'Crédito'), ('DB', 'Débito'), ('TR', 'Transitória')], max_length=2)),
                ('status', models.BooleanField(default=True)),
                ('grupo', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='operacoes.naturezafinanceira')),
            ],
            options={
                'verbose_name': 'Natureza Financeira',
                'verbose_name_plural': 'Naturezas Financeiras',
            },
        ),
        migrations.CreateModel(
            name='RateioCentroDeCusto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_rateio', models.CharField(choices=[('VA', 'Valor'), ('PO', 'Porcentagem')], default='VA', max_length=2, verbose_name='Tipo de Rateio')),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('percentual', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('centro_de_custo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='operacoes.centrodecusto', verbose_name='Centro de Custo')),
                ('movimentacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rateios', to='financeiro.movimentacao')),
            ],
        ),
    ]
