# Generated by Django 5.1.1 on 2024-10-18 01:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Operacoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('AT', 'Ativo'), ('IN', 'Inativo')], default='AT', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='TipoDespesa',
            fields=[
                ('operacoes_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='operacoes.operacoes')),
            ],
            bases=('operacoes.operacoes',),
        ),
        migrations.CreateModel(
            name='TipoPagamento',
            fields=[
                ('operacoes_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='operacoes.operacoes')),
            ],
            bases=('operacoes.operacoes',),
        ),
        migrations.CreateModel(
            name='TipoReceita',
            fields=[
                ('operacoes_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='operacoes.operacoes')),
            ],
            bases=('operacoes.operacoes',),
        ),
    ]
