# Generated by Django 5.1.1 on 2024-10-09 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('tipo', models.CharField(choices=[('pagamento', 'Tipo de Pagamento'), ('despesa', 'Tipo de Despesa'), ('entrada', 'Tipo de Entrada')], max_length=10)),
                ('status', models.CharField(choices=[('AT', 'Ativo'), ('IN', 'Inativo')], default='AT', max_length=10)),
            ],
        ),
    ]
