# Generated by Django 5.1.1 on 2025-02-21 01:28

import django.db.models.deletion
import mptt.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0003_remove_endereco_unique_principal_endereco_per_pessoa_and_more'),
        ('financeiro', '0003_delete_rateiocentrodecusto'),
        ('operacoes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='centrodecusto',
            name='level',
            field=models.PositiveIntegerField(default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='centrodecusto',
            name='lft',
            field=models.PositiveIntegerField(default=1, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='centrodecusto',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subcentros', to='operacoes.centrodecusto'),
        ),
        migrations.AddField(
            model_name='centrodecusto',
            name='rght',
            field=models.PositiveIntegerField(default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='centrodecusto',
            name='tree_id',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='centrodecusto',
            name='responsavel',
            field=models.ForeignKey(blank=True, limit_choices_to={'atributos__tipo': 'CO'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='centros_responsaveis', to='cadastro.pessoa'),
        ),
        migrations.AlterField(
            model_name='naturezafinanceira',
            name='grupo',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='operacoes.naturezafinanceira'),
        ),
        migrations.CreateModel(
            name='RateioCentroDeCusto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_rateio', models.CharField(choices=[('VA', 'Valor'), ('PO', 'Porcentagem')], default='VA', max_length=2, verbose_name='Tipo de Rateio')),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('percentual', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('centro_de_custo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='operacoes.centrodecusto', verbose_name='Centro de Custo')),
                ('movimentacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rateios', to='financeiro.movimentacao')),
            ],
        ),
    ]
