# Generated by Django 5.1.1 on 2025-01-07 01:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0007_alter_cadastro_cnpj_cpf'),
        ('operacoes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='centrodecusto',
            name='responsavel',
            field=models.ForeignKey(blank=True, limit_choices_to={'atributos__tipo': 'CO'}, null=True, on_delete=django.db.models.deletion.PROTECT, to='cadastro.cadastro'),
        ),
    ]
