# Generated by Django 5.1.1 on 2024-10-18 01:25

from django.db import migrations, models

def create_default_tipos_despesas(apps, schema_editor):
    # Obtenha o modelo 'TipoDespesa'
    TipoDespesa = apps.get_model('operacoes', 'TipoDespesa')

    # Crie as despesas padrão
    despesas_default = [
        'Salário',
        'Aluguel',
        'Contas de Serviços',
        'Materiais',
        'Despesas Diversas'
    ]

    for despesa in despesas_default:
        TipoDespesa.objects.create(nome=despesa)

def create_default_tipos_pagamentos(apps, schema_editor):
    # Obtenha o modelo 'TipoPagamento'
    TipoPagamento = apps.get_model('operacoes', 'TipoPagamento')

    # Crie os pagamentos padrão
    pagamentos_default = [
        'Transferência Bancária',
        'Cartão de Crédito',
        'Cartão de Débito',
        'Boleto',
        'Dinheiro'
    ]

    for pagamento in pagamentos_default:
        TipoPagamento.objects.create(nome=pagamento)

def create_default_tipos_receitas(apps, schema_editor):
    # Obtenha o modelo 'TipoReceita'
    TipoReceita = apps.get_model('operacoes', 'TipoReceita')

    # Crie as receitas padrão
    receitas_default = [
        'Venda de Serviços',
        'Consultoria',
        'Receitas de Aluguel',
        'Investimentos',
        'Receitas Diversas'
    ]

    for receita in receitas_default:
        TipoReceita.objects.create(nome=receita)

class Migration(migrations.Migration):

    dependencies = [
        ('operacoes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='operacoes',
            name='xpto',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
            migrations.RunPython(create_default_tipos_receitas),
            migrations.RunPython(create_default_tipos_pagamentos),
            migrations.RunPython(create_default_tipos_despesas),
    ]
