# Generated by Django 5.1.1 on 2024-10-09 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movimentacoes', '0010_entrada_tipo_receita_alter_entrada_tipo_pagamento_and_more'),
        ('operacoes', '0002_tipodespesa_tipopagamento_tiporeceita'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tipo',
        ),
    ]
