# Generated by Django 5.1.1 on 2024-09-29 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_fantasia', models.CharField(max_length=80)),
                ('razao_social', models.CharField(max_length=80)),
                ('cnpj', models.CharField(max_length=14)),
                ('cep', models.CharField(max_length=9)),
                ('endereco', models.CharField(max_length=100)),
                ('numero', models.CharField(max_length=6)),
                ('bairro', models.CharField(max_length=100)),
                ('municipio', models.CharField(max_length=50)),
                ('estado', models.CharField(max_length=100)),
            ],
        ),
    ]
