# Generated by Django 5.1.1 on 2024-10-18 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='xpto',
        ),
    ]
