# Generated by Django 5.1.1 on 2024-09-29 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='complemento',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
