# Generated by Django 5.1.1 on 2024-09-30 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_clientes_complemento'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='tipo_pessoa',
            field=models.CharField(blank=True, choices=[('pf', 'Pessoa física'), ('pj', 'Pessoa jurídica')], max_length=20, null=True),
        ),
    ]
