# Generated by Django 5.1.1 on 2024-09-30 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_clientes_tipo_pessoa'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Clientes',
            new_name='Cliente',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='cnpj',
            new_name='cnpj_cpf',
        ),
    ]
