# Generated by Django 5.1.1 on 2024-10-08 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_rename_clientes_cliente_rename_cnpj_cliente_cnpj_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cnpj_cpf',
            field=models.CharField(max_length=18),
        ),
    ]
